# Generated by Django 4.2.7 on 2023-11-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineSale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorites',
        ),
    ]
