# Generated by Django 4.2.7 on 2023-11-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineSale', '0002_remove_product_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_fields',
        ),
    ]
